### PR TITLE
Make the Circular Dependency exception more useful

### PR DESCRIPTION
**Pull request by pedroreys**
Include the names of the tables that are causing the issue in the exception message.

### CODE REVIEW

**Comment by pedroreys** [comment]
meh

**Comment by StevenTCramer** [comment]
Just saw this pull request after I did mine.  Only key difference is the suggestion that TablesToIgnore may be causing the issue which really isn't a circular reference.  But I like pedroreys message format better.

**Comment by TrymBeast** [comment]
I have implemented a workaround for circular dependencies by disabling the necessary constraints to be able to delete the data. I have implemented only for Sql Server and probably it will need some refactoring, but I can make a pull request with this if anyone interested.

**Comment by jbogard** [comment]
@TrymBeast sure, I'd be happy to at least get a solution started here.

**Comment by jjm340** [comment]
@TrymBeast I would love this as I'm running into this issue and was thinking of doing the same thing!

**Comment by TrymBeast** [comment]
@jjm340 I totally forgot about this, I can make a fork with the solution I implemented tomorrow so you can move on with it, but later I'll create an issue to discuss the optimal solution, as there are some possibilities and in my opinion the most performant the better.

**Comment by jjm340** [comment]
@TrymBeast That would be amazing, because right now Respawn is the best solution I've found to the database state problem with integration tests and our build is broken as a result.  I'd owe you a beer and a half on this one

**Comment by TrymBeast** [comment]
@jjm340 This will take longer then anticipated, I will need to upgrade to VS2017 I think. I'm using 2015.

**Comment by jjm340** [comment]
No worries! As it turns out my issue was not with circular dependencies but with RDS in Amazon

**Comment by jducobu** [comment]
@TrymBeast,

> I have implemented a workaround for circular dependencies by disabling the necessary constraints to be able to delete the data. I have implemented only for Sql Server and probably it will need some refactoring, but I can make a pull request with this if anyone interested.

Do you share you code ?

**Comment by TrymBeast** [comment]
@jducobu I will. Just spent some time merging with the latest version.
Didn't tested it, but now it lacks support for Postgres, SqlServerCe, MySql and Oracle.

**Comment by jbogard** [comment]
FYI I’m working on supporting circular dependencies explicitly through
disabling and enabling constraints.

**Comment by TrymBeast** [comment]
@jbogard Damn! Now I was exciting about finishing this! I was even installing docker on my machine to develop some tests.
So, I've made my code public.
You can look at this [commit](https://github.com/TrymBeast/Respawn/commit/6f8e50673eeb187e6e3f3867000f61dc9c16e40f) it has things that I was going to improve but it's almost there.
Ah btw I found much faster to disable all constraints for a table instead of specific contraints (when we have to disable more than one).

**Comment by jbogard** [comment]
Ah whoops lol

**Comment by jducobu** [comment]
Yesterday I fixed a workaround by deleting the constraints and recreating them after a truncate command.
Disabling and enabling the constraints is probably better, do you confirm ?

**Comment by jbogard** [comment]
Yep! That’s what my approach was going toe.

**Comment by jbogard** [comment]
Circular references are now explicitly supported.

**Pull request closed without merging**
